#!/bin/bash

git clone --bare https://github.com/mozilla-b2g/fxos-certsuite
git clone --bare https://github.com/mozilla-b2g/gaia
git clone --bare https://github.com/mozilla-b2g/gaia-email-libs-and-more
git clone --bare https://github.com/mozilla-b2g/jsas
git clone --bare https://github.com/mozilla-b2g/jswbxml
git clone --bare https://github.com/mozilla-b2g/gecko-partner
git clone --bare https://github.com/mozilla-b2g/gecko-tablet
git clone --bare https://github.com/mozilla-b2g/B2G
git clone --bare https://github.com/mozilla-b2g/platform_frameworks_wilhelm
git clone --bare https://github.com/mozilla-b2g/mail-fakeservers
git clone --bare https://github.com/mozilla-b2g/mocha-tbpl-reporter
git clone --bare https://github.com/mozilla-b2g/platform_external_wpa_supplicant_8
git clone --bare https://github.com/mozilla-b2g/classic-homescreen
git clone --bare https://github.com/mozilla-b2g/device-shinano-common
git clone --bare https://github.com/mozilla-b2g/moztt
git clone --bare https://github.com/mozilla-b2g/platform_frameworks_native
git clone --bare https://github.com/mozilla-b2g/fairphone2_kernel_lk
git clone --bare https://github.com/mozilla-b2g/marketplace-tv-front-end
git clone --bare https://github.com/mozilla-b2g/casting-tutorial
git clone --bare https://github.com/mozilla-b2g/device-shamu-kernel
git clone --bare https://github.com/mozilla-b2g/device-shamu
git clone --bare https://github.com/mozilla-b2g/MozITP
git clone --bare https://github.com/mozilla-b2g/fxos-device-service
git clone --bare https://github.com/mozilla-b2g/platform_external_sepolicy
git clone --bare https://github.com/mozilla-b2g/vendor_broadcom_wlan
git clone --bare https://github.com/mozilla-b2g/mocha-tdd-retry
git clone --bare https://github.com/mozilla-b2g/gecko-periodic-tasks
git clone --bare https://github.com/mozilla-b2g/platform_prebuilts_misc
git clone --bare https://github.com/mozilla-b2g/platform_hardware_realtek
git clone --bare https://github.com/mozilla-b2g/platform_system_netd
git clone --bare https://github.com/mozilla-b2g/brcm_usrlib_dag
git clone --bare https://github.com/mozilla-b2g/automation-projects
git clone --bare https://github.com/mozilla-b2g/mozbench
git clone --bare https://github.com/mozilla-b2g/device_lge_hammerhead-kernel
git clone --bare https://github.com/mozilla-b2g/device_lge_mako-kernel
git clone --bare https://github.com/mozilla-b2g/firefoxos-loop-client
git clone --bare https://github.com/mozilla-b2g/device-flatfish
git clone --bare https://github.com/mozilla-b2g/device-hammerhead
git clone --bare https://github.com/mozilla-b2g/platform_external_bluetooth_bluedroid
git clone --bare https://github.com/mozilla-b2g/i2c-tools
git clone --bare https://github.com/mozilla-b2g/gaia-specs
git clone --bare https://github.com/mozilla-b2g/marionette-device-host
git clone --bare https://github.com/mozilla-b2g/device-flo
git clone --bare https://github.com/mozilla-b2g/platform_frameworks_av
git clone --bare https://github.com/mozilla-b2g/marionette-content-script
git clone --bare https://github.com/mozilla-b2g/marionette-b2gdesktop-host
git clone --bare https://github.com/mozilla-b2g/mozilla-runner
git clone --bare https://github.com/mozilla-b2g/mozilla-profile-builder
git clone --bare https://github.com/mozilla-b2g/dogdish
git clone --bare https://github.com/mozilla-b2g/vex
git clone --bare https://github.com/mozilla-b2g/valgrind
git clone --bare https://github.com/mozilla-b2g/preload-app-toolkit
git clone --bare https://github.com/mozilla-b2g/platform_external_apriori
git clone --bare https://github.com/mozilla-b2g/platform_external_elfutils
git clone --bare https://github.com/mozilla-b2g/gonk-patches
git clone --bare https://github.com/mozilla-b2g/device-grouper
git clone --bare https://github.com/mozilla-b2g/android-device-panda
git clone --bare https://github.com/mozilla-b2g/caldav
git clone --bare https://github.com/mozilla-b2g/hardware_qcom_display
git clone --bare https://github.com/mozilla-b2g/kernel-android-galaxy-s2-ics
git clone --bare https://github.com/mozilla-b2g/android-device-galaxys2
git clone --bare https://github.com/mozilla-b2g/Gaia-UI-Building-Blocks
git clone --bare https://github.com/mozilla-b2g/android-device-tuna
git clone --bare https://github.com/mozilla-b2g/minimal_prebuilt
git clone --bare https://github.com/mozilla-b2g/android-device-crespo
git clone --bare https://github.com/mozilla-b2g/platform_prebuilt
git clone --bare https://github.com/mozilla-b2g/platform_external_oprofile
git clone --bare https://github.com/mozilla-b2g/android-sdk
git clone --bare https://github.com/mozilla-b2g/platform_system_devicesvcd
git clone --bare https://github.com/mozilla-b2g/platform_system_npm
git clone --bare https://github.com/mozilla-b2g/B2GOS-community
git clone --bare https://github.com/mozilla-b2g/platform_system_tvd
git clone --bare https://github.com/mozilla-b2g/platform_system_geolocationd
git clone --bare https://github.com/mozilla-b2g/device-asus-fugu
git clone --bare https://github.com/mozilla-b2g/device_qcom_common
git clone --bare https://github.com/mozilla-b2g/fake-qemu-kernel
git clone --bare https://github.com/mozilla-b2g/platform_system_sensorsd
git clone --bare https://github.com/mozilla-b2g/platform_system_libpdu
git clone --bare https://github.com/mozilla-b2g/platform_hardware_libhardware_moz
git clone --bare https://github.com/mozilla-b2g/extract_elf_ramdisk
git clone --bare https://github.com/mozilla-b2g/gaia-automation
git clone --bare https://github.com/mozilla-b2g/b2g-installer
git clone --bare https://github.com/mozilla-b2g/b2g-installer-builds
git clone --bare https://github.com/mozilla-b2g/platform_hardware_broadcom_libbt
git clone --bare https://github.com/mozilla-b2g/init_sh
git clone --bare https://github.com/mozilla-b2g/bzlite
git clone --bare https://github.com/mozilla-b2g/device-aries
git clone --bare https://github.com/mozilla-b2g/device-shinano
git clone --bare https://github.com/mozilla-b2g/testdroid-client
git clone --bare https://github.com/mozilla-b2g/platform_external_libnfc-pn547
git clone --bare https://github.com/mozilla-b2g/platform_system_bluetoothd
git clone --bare https://github.com/mozilla-b2g/platform_system_libfdio
git clone --bare https://github.com/mozilla-b2g/platform_hardware_libhardware_legacy
git clone --bare https://github.com/mozilla-b2g/platform_external_webrtc
git clone --bare https://github.com/mozilla-b2g/libnfcemu
git clone --bare https://github.com/mozilla-b2g/device-rpi
git clone --bare https://github.com/mozilla-b2g/b2gmonkey
git clone --bare https://github.com/mozilla-b2g/fxos.cdn.mozilla.net
git clone --bare https://github.com/mozilla-b2g/b2g-dashboard
git clone --bare https://github.com/mozilla-b2g/mocha-socket-reporter
git clone --bare https://github.com/mozilla-b2g/darwinstreamingserver
git clone --bare https://github.com/mozilla-b2g/marionette-extension
git clone --bare https://github.com/mozilla-b2g/device-flame
git clone --bare https://github.com/mozilla-b2g/device-sora
git clone --bare https://github.com/mozilla-b2g/gaia-taskenv
git clone --bare https://github.com/mozilla-b2g/device-fugu
git clone --bare https://github.com/mozilla-b2g/marionette-orientation
git clone --bare https://github.com/mozilla-b2g/marionette-file-manager
git clone --bare https://github.com/mozilla-b2g/mozilla-detect-os
git clone --bare https://github.com/mozilla-b2g/mozilla-extract
git clone --bare https://github.com/mozilla-b2g/haida-planning
git clone --bare https://github.com/mozilla-b2g/mozilla-get-url
git clone --bare https://github.com/mozilla-b2g/platform_external_libnfc-nci
git clone --bare https://github.com/mozilla-b2g/npm-mirror
git clone --bare https://github.com/mozilla-b2g/marionette-debug
git clone --bare https://github.com/mozilla-b2g/marionette-settings-api
git clone --bare https://github.com/mozilla-b2g/travis-project-jobs
git clone --bare https://github.com/mozilla-b2g/marionette-plugin-forms
git clone --bare https://github.com/mozilla-b2g/exif-parser
git clone --bare https://github.com/mozilla-b2g/marionette-helper
git clone --bare https://github.com/mozilla-b2g/gaia-profile-builder
git clone --bare https://github.com/mozilla-b2g/device-wasabi
git clone --bare https://github.com/mozilla-b2g/marionette-profile-builder
git clone --bare https://github.com/mozilla-b2g/marionette-firefox-host
git clone --bare https://github.com/mozilla-b2g/mocha-json-proxy
git clone --bare https://github.com/mozilla-b2g/marionette-js-runner
git clone --bare https://github.com/mozilla-b2g/device-helix
git clone --bare https://github.com/mozilla-b2g/marionette-apps
git clone --bare https://github.com/mozilla-b2g/sockit-to-me
git clone --bare https://github.com/mozilla-b2g/marionette-js-logger
git clone --bare https://github.com/mozilla-b2g/mozilla-download
git clone --bare https://github.com/mozilla-b2g/qa-testcase-data
git clone --bare https://github.com/mozilla-b2g/device_generic_goldfish
git clone --bare https://github.com/mozilla-b2g/device-leo
git clone --bare https://github.com/mozilla-b2g/device-inari
git clone --bare https://github.com/mozilla-b2g/device-gp-keon
git clone --bare https://github.com/mozilla-b2g/platform_external_elfcopy
git clone --bare https://github.com/mozilla-b2g/android-device-hamachi
git clone --bare https://github.com/mozilla-b2g/dogfood-setup
git clone --bare https://github.com/mozilla-b2g/librecovery
git clone --bare https://github.com/mozilla-b2g/android-device-unagi
git clone --bare https://github.com/mozilla-b2g/adb-push
git clone --bare https://github.com/mozilla-b2g/screencap-gonk
git clone --bare https://github.com/mozilla-b2g/android-device-m4
git clone --bare https://github.com/mozilla-b2g/fake-libdvm
git clone --bare https://github.com/mozilla-b2g/android-device-crespo4g
git clone --bare https://github.com/mozilla-b2g/platform_external_opensans
git clone --bare https://github.com/mozilla-b2g/android-device-maguro
git clone --bare https://github.com/mozilla-b2g/wpa_supplicant_8_lib
git clone --bare https://github.com/mozilla-b2g/android-device-otoro
git clone --bare https://github.com/mozilla-b2g/gaia-botio-scripts
git clone --bare https://github.com/mozilla-b2g/b2g-manifest
git clone --bare https://github.com/mozilla-b2g/marionette-js-client
git clone --bare https://github.com/mozilla-b2g/initramfs-galaxy-s2-ics
git clone --bare https://github.com/mozilla-b2g/gonk-ics-manifest
git clone --bare https://github.com/mozilla-b2g/gonk-misc
git clone --bare https://github.com/mozilla-b2g/fake-dalvik
git clone --bare https://github.com/mozilla-b2g/b2g-toolchains
git clone --bare https://github.com/mozilla-b2g/android-hardware-libhardware
git clone --bare https://github.com/mozilla-b2g/android-system-vold
git clone --bare https://github.com/mozilla-b2g/android-hardware_legacy
git clone --bare https://github.com/mozilla-b2g/android-hardware-ril
git clone --bare https://github.com/mozilla-b2g/rilproxy
git clone --bare https://github.com/mozilla-b2g/gecko-b2g
git clone --bare https://github.com/mozilla-b2g/codeaurora_kernel_msm
git clone --bare https://github.com/mozilla-b2g/device-fairphone2
git clone --bare https://github.com/mozilla-b2g/platform_build
git clone --bare https://github.com/mozilla-b2g/device-sony-flamingo
git clone --bare https://github.com/mozilla-b2g/device-openc
git clone --bare https://github.com/mozilla-b2g/platform_external_node
git clone --bare https://github.com/mozilla-b2g/device-sony-castor
git clone --bare https://github.com/mozilla-b2g/device-sony-castor_windy
git clone --bare https://github.com/mozilla-b2g/device-sony-scorpion_windy
git clone --bare https://github.com/mozilla-b2g/device-sony-scorpion
git clone --bare https://github.com/mozilla-b2g/device-sony-common
git clone --bare https://github.com/mozilla-b2g/device-sony-aries
git clone --bare https://github.com/mozilla-b2g/device-sony-leo
git clone --bare https://github.com/mozilla-b2g/device-sony-sirius
git clone --bare https://github.com/mozilla-b2g/device-sony-honami
git clone --bare https://github.com/mozilla-b2g/device-sony-amami
git clone --bare https://github.com/mozilla-b2g/device-sony-tianchi
git clone --bare https://github.com/mozilla-b2g/device-sony-shinano
git clone --bare https://github.com/mozilla-b2g/device-sony-rhine
git clone --bare https://github.com/mozilla-b2g/device-sony-yukon
git clone --bare https://github.com/mozilla-b2g/device-sony-eagle
git clone --bare https://github.com/mozilla-b2g/device-sony-seagull
git clone --bare https://github.com/mozilla-b2g/platform_bootable_recovery
git clone --bare https://github.com/mozilla-b2g/device_asus_fugu-kernel
git clone --bare https://github.com/mozilla-b2g/device-google-atv
git clone --bare https://github.com/mozilla-b2g/platform_system_nfcd
git clone --bare https://github.com/mozilla-b2g/mkqcdtbootimg
git clone --bare https://github.com/mozilla-b2g/platform_external_libxml2
git clone --bare https://github.com/mozilla-b2g/device-rpi2b
git clone --bare https://github.com/mozilla-b2g/device-mako
git clone --bare https://github.com/mozilla-b2g/nginx
git clone --bare https://github.com/mozilla-b2g/bleach.js
git clone --bare https://github.com/mozilla-b2g/macaddrsetup
git clone --bare https://github.com/mozilla-b2g/timekeep
git clone --bare https://github.com/mozilla-b2g/notes
git clone --bare https://github.com/mozilla-b2g/rpi-linux
git clone --bare https://github.com/mozilla-b2g/android_external_busybox
git clone --bare https://github.com/mozilla-b2g/external_mesa3d
git clone --bare https://github.com/mozilla-b2g/gralloc-rpi2b
git clone --bare https://github.com/mozilla-b2g/kernel-x86_64
git clone --bare https://github.com/mozilla-b2g/vendor-qcom-opensource-dataservices
git clone --bare https://github.com/mozilla-b2g/platform_external_qemu
git clone --bare https://github.com/mozilla-b2g/platform_prebuilts_qemu-kernel
git clone --bare https://github.com/mozilla-b2g/kernel_goldfish
git clone --bare https://github.com/mozilla-b2g/platform_frameworks_base
git clone --bare https://github.com/mozilla-b2g/platform_hardware_ril
git clone --bare https://github.com/mozilla-b2g/external_skia
git clone --bare https://github.com/mozilla-b2g/hardware_qcom_wlan
git clone --bare https://github.com/mozilla-b2g/hardware_qcom_media
git clone --bare https://github.com/mozilla-b2g/hardware_qcom_gps
git clone --bare https://github.com/mozilla-b2g/hardware_qcom_camera
git clone --bare https://github.com/mozilla-b2g/hardware_qcom_bt
git clone --bare https://github.com/mozilla-b2g/hardware_qcom_audio
git clone --bare https://github.com/mozilla-b2g/platform_system_core
git clone --bare https://github.com/mozilla-b2g/hwcomposer-rpi2b
git clone --bare https://github.com/mozilla-b2g/platform_hardware_libhardware
git clone --bare https://github.com/mozilla-b2g/device-qcom-sepolicy
git clone --bare https://github.com/mozilla-b2g/thermanager
git clone --bare https://github.com/mozilla-b2g/kernel_lk
git clone --bare https://github.com/mozilla-b2g/platform_external_libpng
git clone --bare https://github.com/mozilla-b2g/android-development
git clone --bare https://github.com/mozilla-b2g/gaia-node-modules
git clone --bare https://github.com/mozilla-b2g/platform_bionic
git clone --bare https://github.com/mozilla-b2g/sony-camera-hal
git clone --bare https://github.com/mozilla-b2g/fxos-appgen
git clone --bare https://github.com/mozilla-b2g/webmaker-fxos
git clone --bare https://github.com/mozilla-b2g/libdrm-rpi2b
git clone --bare https://github.com/mozilla-b2g/nomnom
git clone --bare https://github.com/mozilla-b2g/vendor-sony-kernel
git clone --bare https://github.com/mozilla-b2g/orangutan
git clone --bare https://github.com/mozilla-b2g/gaia-preload
git clone --bare https://github.com/mozilla-b2g/raptor-ui
git clone --bare https://github.com/mozilla-b2g/js-test-agent
git clone --bare https://github.com/mozilla-b2g/unbootimg
git clone --bare https://github.com/mozilla-b2g/skia-b2g-sgs2
git clone --bare https://github.com/mozilla-b2g/kernel_flatfish
git clone --bare https://github.com/mozilla-b2g/node-uuid
git clone --bare https://github.com/mozilla-b2g/uplift
git clone --bare https://github.com/mozilla-b2g/bisect_b2g
git clone --bare https://github.com/mozilla-b2g/ubersicht
git clone --bare https://github.com/mozilla-b2g/ntpclient-android
git clone --bare https://github.com/mozilla-b2g/marionette-debug-server
git clone --bare https://github.com/mozilla-b2g/boing
git clone --bare https://github.com/mozilla-b2g/kernel-omap
git clone --bare https://github.com/mozilla-b2g/platform_external_dbus
git clone --bare https://github.com/mozilla-b2g/busybox
git clone --bare https://github.com/mozilla-b2g/android_system_bluetooth
